name: sakura_blizzard
description: This is a 3D effect related to flower petals in Flutter. Cherry blossom petals are included as standard.
version: 6.0.3
repository: https://github.com/MasahideMori-SimpleAppli/sakura_blizzard

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  simple_3d: ^16.1.1
  simple_3d_renderer: ^22.1.0
  util_simple_3d: ^12.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  simple_lint: ^1.0.0
